# Generated by Django 3.2.8 on 2021-11-11 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preprod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mise_a_jour', models.DateField(verbose_name='date de mise à jour')),
                ('machine', models.CharField(choices=[('MAR1', 'MAR1'), ('MAR2', 'MAR2')], default='MAR1', max_length=4)),
                ('pack_id', models.IntegerField(unique=True, verbose_name='ID du Pck')),
                ('odc', models.IntegerField(verbose_name='N° ODC')),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('carte_perso_ok', models.IntegerField(verbose_name='carte personalisé ok')),
                ('rejet_machine', models.IntegerField(verbose_name='rejets de la machine')),
                ('retoure_stock', models.IntegerField(verbose_name='Retour au stock')),
                ('autres', models.IntegerField(default=0, verbose_name='autres problèmes')),
                ('date_de_creation', models.DateField(auto_now_add=True, verbose_name='date de 1er creation')),
                ('commentaire', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Qcontrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mise_a_jour', models.DateField(null=True, verbose_name='date de mise à jour')),
                ('carte_embalee', models.IntegerField(null=True)),
                ('ab', models.IntegerField(null=True)),
                ('reprod', models.IntegerField(null=True)),
                ('autres', models.IntegerField(default=0)),
                ('commentaire', models.CharField(blank=True, max_length=1000)),
                ('preprod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Qprod', to='prod.preprod')),
            ],
        ),
        migrations.CreateModel(
            name='Rejprod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mise_a_jour', models.DateField(verbose_name='date de mise à jour')),
                ('nd', models.IntegerField(null=True)),
                ('autres', models.IntegerField(default=0)),
                ('commentaire', models.CharField(blank=True, max_length=1000)),
                ('qcontrol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Rctrl', to='prod.qcontrol')),
            ],
        ),
    ]
