# Generated by Django 3.2.8 on 2021-11-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preprod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mise_a_jour', models.DateField(verbose_name='date de mise à jour')),
                ('machine_name', models.CharField(max_length=64)),
                ('pack_id', models.IntegerField(unique=True)),
                ('odc', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('carte_perso_ok', models.IntegerField()),
                ('rejet_machine', models.IntegerField()),
                ('retoure_stock', models.IntegerField()),
                ('autres', models.IntegerField(default=0)),
                ('date_de_creation', models.DateField(auto_now_add=True, verbose_name='date de 1er creation')),
                ('commentaire', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Rejprod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mise_a_jour', models.DateField(verbose_name='date de mise à jour')),
                ('quantite', models.IntegerField()),
                ('carte_ok', models.IntegerField()),
                ('rejet', models.IntegerField()),
                ('retoure_stock', models.IntegerField()),
                ('autres', models.IntegerField(default=0)),
                ('commentaire', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Qcontrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mise_a_jour', models.DateField(verbose_name='date de mise à jour')),
                ('carte_ok', models.IntegerField()),
                ('rejet', models.IntegerField()),
                ('retoure_stock', models.IntegerField()),
                ('autres', models.IntegerField(default=0)),
                ('commentaire', models.CharField(blank=True, max_length=1000)),
                ('preprod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Qprod', to='prod.preprod')),
            ],
        ),
    ]
