# Generated by Django 3.2.8 on 2021-11-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcontrol',
            name='carte_ok',
            field=models.IntegerField(null=True),
        ),
    ]
