# Generated by Django 3.2.8 on 2021-10-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preprod',
            old_name='machine',
            new_name='commentaire',
        ),
        migrations.AddField(
            model_name='preprod',
            name='machine_name',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
