# Generated by Django 3.2.8 on 2021-10-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejprod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mise_a_jour', models.DateField(verbose_name='date de mise à jour')),
                ('quantite', models.IntegerField()),
                ('carte_ok', models.IntegerField()),
                ('rejet', models.IntegerField()),
                ('retoure_stock', models.IntegerField()),
                ('autres', models.IntegerField(default=0)),
                ('commentaire', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
