# Generated by Django 3.2.8 on 2021-11-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0002_alter_qcontrol_carte_ok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcontrol',
            name='date_mise_a_jour',
            field=models.DateField(null=True, verbose_name='date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='qcontrol',
            name='rejet',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='qcontrol',
            name='retoure_stock',
            field=models.IntegerField(null=True),
        ),
    ]
