# Generated by Django 3.2.8 on 2021-10-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0002_auto_20211019_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprod',
            name='date_mise_a_jour',
            field=models.DateField(verbose_name='date de mise à jour'),
        ),
    ]
